CREATE TABLE [dbo].[Notas] (
    [Id_NOTAS]      INT          NOT NULL,
    [ID_MATERIA]    INT          NULL,
    [ID_ESTUDIANTE] INT          NULL,
    [ID_MODALIDAD]  INT          NULL,
    [NOTA 1]        NUMERIC (18) NULL,
    [NOTA 2]        NUMERIC (18) NULL,
    [NOTA 3]        NUMERIC (18) NULL,
    [PROMEDIO]      NUMERIC (18) NULL,
    [ID_PERIODO]    INT          NULL,
    PRIMARY KEY CLUSTERED ([Id_NOTAS] ASC), 
	CONSTRAINT [ID_MATERIA] FOREIGN KEY ([ID_MATERIA]) REFERENCES [dbo].[MATERIAS] ([ID_MATERIAS]), 
	CONSTRAINT [ID_ESTUDIANTE] FOREIGN KEY ([ID_ESTUDIANTE]) REFERENCES [dbo].[Estudiante] ([ID_ESTUDIANTE]), 
	



	
);

